# Generated by Django 3.2.4 on 2022-12-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('company', models.TextField(max_length=100)),
                ('heading', models.TextField(max_length=500)),
                ('info', models.TextField(max_length=10000)),
                ('date', models.DateField()),
            ],
        ),
    ]
