# Generated by Django 3.2.4 on 2022-12-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stringID', models.TextField(max_length=29)),
                ('company', models.TextField(max_length=100)),
                ('postedBy', models.TextField(max_length=100)),
                ('postTime', models.DateTimeField()),
                ('deadLine', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='database',
            name='date',
        ),
        migrations.AddField(
            model_name='database',
            name='stringID',
            field=models.TextField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
