# Generated by Django 3.2.4 on 2022-12-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_company_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='info',
            field=models.TextField(max_length=500),
        ),
    ]
