# Generated by Django 3.2.4 on 2022-12-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_company_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eligibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stringId', models.TextField(max_length=100)),
                ('no', models.IntegerField()),
                ('company', models.TextField(max_length=100)),
                ('heading', models.TextField(max_length=500)),
                ('info', models.TextField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='stringID',
            field=models.TextField(max_length=100),
        ),
    ]
