# Generated by Django 3.2.4 on 2022-12-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20221217_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='link',
            field=models.URLField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
