# Generated by Django 3.2.4 on 2022-12-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_company_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stringId', models.TextField(max_length=100)),
                ('company', models.TextField(max_length=100)),
                ('postedBy', models.TextField(max_length=100)),
                ('postTime', models.DateTimeField()),
                ('deadLine', models.DateField()),
                ('package', models.TextField(max_length=29)),
                ('info', models.TextField(max_length=500)),
                ('link', models.URLField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
