# Generated by Django 3.2.4 on 2022-12-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_internships'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='stringID',
            new_name='stringId',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='stringID',
            new_name='stringId',
        ),
    ]
