# Generated by Django 3.2.4 on 2022-12-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20221229_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stringId', models.TextField(max_length=100)),
                ('name', models.TextField(max_length=100)),
                ('startDateTime', models.DateTimeField()),
                ('EndDateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContestDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stringId', models.TextField(max_length=100)),
                ('no', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('solution', models.ImageField(upload_to='solutions/')),
            ],
        ),
    ]
