# Generated by Django 3.2.4 on 2022-12-31 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_contest_contestdatabase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='company',
        ),
        migrations.RemoveField(
            model_name='eligibilities',
            name='company',
        ),
    ]
